neme:GitHub Actions Demo
on:push
jobs :
  hellos:
    runs-on:ubuntu-latest
    explor-github-actions:
      -name:print branch name
       run:echo"branch name is ${{GitHub.ref}} "
      -name:print os name
       run:echo"our os is${{GitHub.os}}"
      -name:print event name 
       run:echo"${{GitHub.event_name}}"
      -name:print repository name 
       run:echo"${{github.repository }}"
      -name:list files
       run:ls${{github.workspace}}
      -name:checkout repository action
       uses:actions/checkout@v3
